### ISSUE TITLE
`get_fiona_type_from_pydata` does not support lists

### ISSUE THREAD

**Issue by huard** [NCPP/ocgis#512]
Sometimes in the properties field of a geometry, there is a bbox field with a list of values. Lists are not supported by `get_fiona_type_from_pydata`.

**Comment by bekozi** [comment]
It should be relatively trivial to detect if `pydata` is a sequence and use the first element as an archetype. Would this address the issue? I don't have a good sense for the context.

**Comment by huard** [comment]
I don't know. I just noticed that some properties with list crashed this function, but I don't know what role it plays exactly.

So I'm fetching geometries from a WFS server and load them as shapely objects (`geom`) with `crs` and `properties`. I then pass those geometries as a list of dict to OcgOperations. 

For the moment I just replaced the properties whose values are a list by a string with an error message. Any improvement over this makeshift solution is going to be welcome.

**Comment by bekozi** [comment]
Got it. I'll take a look and get back to you. Thanks for the additional info.

**Comment by bekozi** [comment]
@huard: Since `fiona` properties are always scalars and `from_records` expects this, I can think of a few options:
* Strip lists and issue a warning. 
* Specialize the conversion and allow lists in the properties which will then create multi-dimensional arrays.
* Issue a more explicit error message. If this is encountered, you can use  `','.join(<list property>)` to convert the list to a string. This would then cleanly get converted to a field and be pretty obvious as to how it is used if the bounding box is later needed.

Which do you think works best for your case?

**Comment by huard** [comment]
No strong opinion, I'm happy with the first and simplest option.

**Comment by bekozi** [comment]
Okay, pushed a fix to master. Let me know how it goes. A warning is just issued for a list/tuple in properties.

**Comment by bekozi** [comment]
@huard, I realized I needed to mention that the property is skipped in addition to emitting a warning! Oops.

**Comment by huard** [comment]
Looking good. Thanks !
